#!/bin/bash
echo ------------------------------Activating environment
source .venv/bin/activate
echo ------------------------------Launching Exp $1
cd code
python engine.py experiment$1
echo ------------------------------Terminated